[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# Edge Functions for SPA routing
[[edge_functions]]
  path = "/*"
  function = "netlify"

# Primary redirect for SPA - this will be used if the edge function fails
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Set cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable pre-rendering for performance (optional)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
