[build]
  publish = "dist"
  command = "npm run build"
  # Add functions directory if you later add Netlify functions
  # functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  
# Handle SPA routing - Always return index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable pre-rendering for performance (optional)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
